### ISSUE TITLE
INFO: Running unit tests on Windows

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/circe-be#120]
I faced an issue where unit tests were failing due to lack of permissions. This appears to be environment specific to my version of Windows (Windows Server 2012 R2 Server). Posting it here in case it helps others.

Here was the error I received:

````
-------------------------------------------------------------------------------
Test set: org.ohdsi.circe.cohortdefinition.CohortGeneration_5_0_0_Test
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.533 sec <<< FAILURE! - in org.ohdsi.circe.cohortdefinition.CohortGeneration_5_0_0_Test
org.ohdsi.circe.cohortdefinition.CohortGeneration_5_0_0_Test  Time elapsed: 0.533 sec  <<< ERROR!
java.lang.IllegalStateException: Process [E:\TEMP\embedded-pg\PG-5f9ef1f42cb476990f9b309e807d5df6\bin\initdb.exe, -A, trust, -U, postgres, -D, E:\TEMP\epg4599625811249145042, -E, UTF-8] failed

	at com.opentable.db.postgres.embedded.EmbeddedPostgres.system(EmbeddedPostgres.java:602)
	at com.opentable.db.postgres.embedded.EmbeddedPostgres.initdb(EmbeddedPostgres.java:221)
	at com.opentable.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:142)
	at com.opentable.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:554)
	at com.opentable.db.postgres.junit.SingleInstancePostgresRule.pg(SingleInstancePostgresRule.java:46)
	at com.opentable.db.postgres.junit.SingleInstancePostgresRule.before(SingleInstancePostgresRule.java:39)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
````

### Fix

My work-around was to change the permissions on `E:\TEMP` to grant the user `<local machine>\Everyone` with full rights to the folder and subdirectories. Once I set this, I was able to run the unit tests without issue.

**Comment by chrisknoll** [comment]
Good to know, we'll close this issue as a discussion ticket, and if there's an action that we need to take, we'll re-open this as an issue, but for now, I don't think there's any specific action we need to take for the codebase.
